[MODORDSTOR-259] - Added acquisition method API
folio-org/mod-orders-storage pull request #278
Opened 2021-11-23 17:49 UTC by Dmitriy-Butramyou

## Purpose
Add acquisition method API

## Approach
Creader migration
Added system value in acquisition_method table
Added API

#### TODOS and Open Questions

## Learning

@folio-org/acquisitions

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-11-23 17:53 UTC, Dmitriy-Butramyou commented
Working of  the migration verified by postman
![image](https://user-images.githubusercontent.com/49509644/143077842-f7c79ba5-75a0-4c0f-a278-5403509d4aa2.png)

2021-11-24 06:31 UTC, AndreiMPV requested changes

2021-11-24 06:31 UTC, AndreiMPV commented on descriptors/ModuleDescriptor-template.json
> +          "permissionsRequired": ["orders-storage.acquisition-methods.get"]
Should be "orders-storage.acquisition-methods.collection.get"

2021-11-24 06:31 UTC, AndreiMPV commented on descriptors/ModuleDescriptor-template.json
> +      "permissionName" : "orders-storage.acquisition-methods.get",
Same "orders-storage.acquisition-methods.collection.get"

2021-11-24 06:31 UTC, AndreiMPV commented on descriptors/ModuleDescriptor-template.json
> +          "permissionsRequired": ["orders-storage.acquisition-method.delete"]
Should be "orders-storage.acquisition-method.item.delete"

2021-11-24 06:31 UTC, AndreiMPV commented on descriptors/ModuleDescriptor-template.json
> +      "permissionName" : "orders-storage.acquisition-method.delete",
Should be "orders-storage.acquisition-method.item.delete"

2021-11-24 13:05 UTC, AndreiMPV approved these changes

2021-11-25 10:52 UTC, mogrim approved these changes

2021-11-25 10:53 UTC, merged